#!user/bin/python3
import sys
 
 
f = open(sys.argv[1], 'r')
while True:
    for line in f:
        i = 2
        lin = int(line)
        for i in range(round(lin/2 + 2)):
            if i > 1 and lin % i == 0:
                j = round(lin / i)
                print(f"{lin}={j}*{i}")
                break
            i += 1
    break 
